Gates 17-48
gummyboars/lunboks pull request #185
Opened 2023-02-01 07:54 UTC by petercombs

2023-03-19 22:07 UTC, fingoldfish requested changes

2023-03-19 22:07 UTC, fingoldfish commented on eldritch/test_gates.py
> +
Can you also add a test for Other48?

2023-03-22 00:50 UTC, petercombs commented on eldritch/gate_encounters.py
> +  return events.PassFail(char, events.Check(char, "lore", -2), events.Nothing(), knowledge)
Somehow being flooded with knowledge must have felt worse to me than "Nothing happens".

2023-03-25 22:24 UTC, fingoldfish requested changes

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  rites = events.Loss(char, {"sanity": 3, "stamina": 3})
If you fail the check, you are also delayed.

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  ])
Attach the character to this sequence

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  ])
Attach the character to this sequence.

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  ])
Attach the character to this sequence.

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  ])
Attach the character to this sequence.

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  ])
Attach the character to this sequence.

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  ])
Attach the character to this sequence.

2023-03-25 22:24 UTC, fingoldfish commented on eldritch/test_gates.py
> +
A few more tests I would like to see: Other23, Other24, and Dreamlands28 (make sure being devoured works).

2023-03-26 21:59 UTC, fingoldfish commented on eldritch/gate_encounters.py
> +  return events.Draw(char, "spell", 1)
Should be "spells", not "spell"

2023-04-01 17:49 UTC, fingoldfish approved these changes

2023-04-01 20:12 UTC, merged