Write some Tomes
gummyboars/lunboks pull request #206
Opened 2023-05-11 04:53 UTC by petercombs

Technically all the tomes.

2023-05-13 16:31 UTC, fingoldfish requested changes

2023-05-13 16:31 UTC, fingoldfish commented on eldritch/items/unique.py
> +    self.max_tokens["stamina"] = 2
Add a max tokens event?

2023-05-13 16:31 UTC, fingoldfish commented on eldritch/items/unique.py
> +        events.Loss(owner, {"sanity": 1}, source=self),
I would recommend putting the token before the sanity loss - that way, if they go insane, they still put the token on the tome.

2023-05-13 16:31 UTC, fingoldfish commented on eldritch/items/unique.py
> +        events.GainOrLoss(owner, gains={"clues": 1}, losses={"sanity": 2}, source=self),
Same here and below - discard before the loss.

2023-05-13 16:31 UTC, fingoldfish commented on eldritch/items/unique.py
> +  "Necronomicon"
Might have forgotten something here.

2023-05-13 16:31 UTC, fingoldfish commented on eldritch/items/unique.py
> +from .base import Item, Weapon, OneshotWeapon, Tome
Don't forget to add the new tomes to `__all__`, and also create them in the Create() functions. And also remove the TODO that references the tomes.

2023-05-13 16:31 UTC, fingoldfish commented on eldritch/items/unique.py
> +    return events.PassFail(owner, check, success, events.Nothing())
Can I request that you add a test that covers all of the tomes? Something like
```
for tome in list_of_tomes:
  char.possessions = [tome]
  resolve_to_choice(CityChoice)
  assert tome.handle in state.usables
```
Would be good to get coverage on the creation of the read events.

2023-05-13 16:50 UTC, petercombs commented on eldritch/items/unique.py
> +    self.max_tokens["stamina"] = 2
`Item.get_max_token_event` already returns `DiscardSpecific(owner, [self])`

2023-05-14 05:42 UTC, fingoldfish approved these changes

2023-05-14 05:42 UTC, fingoldfish commented on eldritch/items/common.py
> +class OldJournal(Tome):
You forgot to add this to `__all__` and `CreateCommon`

2023-05-14 17:00 UTC, merged