Allow ancient ones to tweak the world upon choosing them
gummyboars/lunboks pull request #208
Opened 2023-06-10 18:10 UTC by petercombs

This allows Squidface to reduce the maximum sanity/stamina of characters from the very beginning of the game, rather than letting them effectively have a bonus san/stam that they can't refill.

2023-06-10 18:13 UTC, petercombs commented
I wasn't sure how to write a test, but running the server this has the expected behavior: choosing a character, then Squidface reduces their stats, then changing the choice to another AO restores it to the max.

2023-06-11 02:00 UTC, fingoldfish commented
I think this was already fixed in https://github.com/gummyboars/lunboks/commit/43a02beaae2663dd1d03879bec0e25a7a35073b7
Though if we need setup for other ancient ones, we can add it.

2023-06-11 02:11 UTC, petercombs commented
I think some mechanism like this will also be useful for adding Masks.

2023-06-11 02:45 UTC, fingoldfish requested changes

2023-06-11 02:45 UTC, fingoldfish commented on eldritch/eldritch.py
> +    self.ancient_one.setup(self)
Can I ask you to move this from handle_ancient to handle_start? If we want to do something like adding masks, we don't want to have to remove the masks when the player changes their minds about which ancient one to fight.

2023-06-11 07:18 UTC, fingoldfish approved these changes

2023-06-11 08:37 UTC, merged