Implementable Mythos
gummyboars/lunboks pull request #21
Opened 2021-05-09 06:26 UTC by petercombs

2021-05-09 09:01 UTC, fingoldfish requested changes

2021-05-09 09:01 UTC, fingoldfish commented on eldritch/mythos.py
> +    return self.ReturnToCup('streets')
I think you mean events.ReturnToCup.

2021-05-10 01:56 UTC, petercombs commented on eldritch/mythos.py
> +    if isinstance(event, events.EndMovement) and char.place.name == "Northside":
If it's an EndMovement event, though, won't that have a character?

2021-05-16 13:54 UTC, fingoldfish commented on eldritch/mythos.py
> +    if attribute == "luck":
Same comment - only applies to characters in the city.

2021-05-16 13:54 UTC, fingoldfish commented on eldritch/mythos.py
> +    if isinstance(event, events.EndMovement) and char.place.name == "Northside":
That's my mistake. I didn't read carefully enough. Though I'm curious why this isn't just
if isinstance(...) and event.character.place.name ...

2021-05-16 13:54 UTC, fingoldfish commented on eldritch/mythos.py
> +      return events.Sequence([gain, wonders])
Ah, but the character is actually used in a different place - it's used when a character goes insane. You see, when a character goes insane, the event stack has to be cleared of anything the character was doing at the time (e.g. fighting monsters, having an encounter). But you wouldn't want to clear any events caused by something unrelated to the character (e.g. drawing and resolving a mythos card). Sequence events with the character attached to them will get cleared from the stack if the character goes insane, other Sequence events will not.

In this case, I think you do want to add the character to the Sequence - if there are multiple things that can happen when the character ends their movement in the streets, and this particular one causes the character to go insane, then the other events shouldn't happen. I'm not sure what those other events would be, but better to have it and not need it than to need it and not have it.

2021-05-16 15:30 UTC, petercombs commented on eldritch/mythos.py
> +    if isinstance(event, events.EndMovement) and char.place.name == "Northside":
Mainly so the stuff inside the if block can also use the `char` variable, rather than the longer `event.character`

2021-05-24 02:23 UTC, merged